/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.store.view;

/**
 *
 * @author FAMILIA
 */
public class PanelCustomerAdd extends javax.swing.JPanel {

    /**
     * Creates new form PanelAddClient
     */
    public PanelCustomerAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanelCustomer = new javax.swing.JTabbedPane();
        tabCustomerBasic = new javax.swing.JPanel();
        panelCustomerBasic = new javax.swing.JPanel();
        lblCustomerBasicName = new javax.swing.JLabel();
        txtCustomerBasicName = new javax.swing.JTextField();
        lblCustomerBasicDocument = new javax.swing.JLabel();
        cbCustomerBasicDocumentType = new javax.swing.JComboBox<>();
        txtCustomerBasicDocument = new javax.swing.JFormattedTextField();
        cbCustomerBasicMaritalStatus = new javax.swing.JComboBox<>();
        lblCustomerBasicMaritalSatus = new javax.swing.JLabel();
        txtCustomerBasicBirthDate = new javax.swing.JFormattedTextField();
        lblCustomerBasicBirthDate = new javax.swing.JLabel();
        cbCustomerBasicGender = new javax.swing.JComboBox<>();
        lblCustomerBasicGender = new javax.swing.JLabel();
        btnCustomerBasicNext = new javax.swing.JButton();
        tabCustomerAddress = new javax.swing.JPanel();
        panelCustomerAddress = new javax.swing.JPanel();
        cbCustomerAddressPublicPlaceType = new javax.swing.JComboBox<>();
        lblCustomerAddressPublicPlaceType = new javax.swing.JLabel();
        lblCustomerAddressPublicPlace = new javax.swing.JLabel();
        txtCustomerAddressPublicPlace = new javax.swing.JTextField();
        lblCustomerAddressNumber = new javax.swing.JLabel();
        txtCustomerAddressNumber = new javax.swing.JTextField();
        lblCustomerAddressDistrict = new javax.swing.JLabel();
        txtCustomerAddressDistrict = new javax.swing.JTextField();
        lblCustomerAddressComplement = new javax.swing.JLabel();
        txtCustomerAddressComplement = new javax.swing.JTextField();
        lblCustomerAddressState = new javax.swing.JLabel();
        cbCustomerAddressState = new javax.swing.JComboBox<>();
        lblCustomerAddressCity = new javax.swing.JLabel();
        cbCustomerAddressCity = new javax.swing.JComboBox<>();
        lblCustomerAddressZipCode = new javax.swing.JLabel();
        txtCustomerAddressZipCode = new javax.swing.JFormattedTextField();
        btnAddressNext = new javax.swing.JButton();
        btnAddressBack = new javax.swing.JButton();
        tabCustomerContact = new javax.swing.JPanel();
        paneCustomerlContact = new javax.swing.JPanel();
        cbCustomerContactContactType = new javax.swing.JComboBox<>();
        lblCustomerContactContactType = new javax.swing.JLabel();
        txtCustomerContactValue = new javax.swing.JTextField();
        scrollCustomerContact = new javax.swing.JScrollPane();
        tableCustomerContact = new javax.swing.JTable();
        btnCustomerContactNew = new javax.swing.JButton();
        btnCustomerContactDelete = new javax.swing.JButton();
        btnCustomerContactSave = new javax.swing.JButton();
        btnCustomerContactBack = new javax.swing.JButton();
        btnCustomerContactCustomerSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tabCustomerBasic.setBackground(new java.awt.Color(255, 255, 255));

        panelCustomerBasic.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomerBasic.setBorder(javax.swing.BorderFactory.createTitledBorder("Básico"));

        lblCustomerBasicName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerBasicName.setText("Nome:");

        txtCustomerBasicName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerBasicNameActionPerformed(evt);
            }
        });

        lblCustomerBasicDocument.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerBasicDocument.setText("Documento:");

        cbCustomerBasicDocumentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCustomerBasicMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCustomerBasicMaritalSatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerBasicMaritalSatus.setText("Estado Civil:");

        lblCustomerBasicBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerBasicBirthDate.setText("Data de nascimento:");

        cbCustomerBasicGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCustomerBasicGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerBasicGender.setText("Sexo:");

        javax.swing.GroupLayout panelCustomerBasicLayout = new javax.swing.GroupLayout(panelCustomerBasic);
        panelCustomerBasic.setLayout(panelCustomerBasicLayout);
        panelCustomerBasicLayout.setHorizontalGroup(
            panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCustomerBasicGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustomerBasicMaritalSatus, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addComponent(lblCustomerBasicBirthDate)
                        .addComponent(lblCustomerBasicName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCustomerBasicDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCustomerBasicMaritalStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbCustomerBasicGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCustomerBasicLayout.createSequentialGroup()
                        .addComponent(cbCustomerBasicDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerBasicDocument, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE))
                    .addComponent(txtCustomerBasicName)
                    .addComponent(txtCustomerBasicBirthDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelCustomerBasicLayout.setVerticalGroup(
            panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerBasicLayout.createSequentialGroup()
                .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCustomerBasicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerBasicName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustomerBasicLayout.createSequentialGroup()
                        .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCustomerBasicDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerBasicDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerBasicDocument))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerBasicBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCustomerBasicBirthDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerBasicGender)
                    .addComponent(cbCustomerBasicGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerBasicMaritalSatus)
                    .addComponent(cbCustomerBasicMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCustomerBasicNext.setText("Próximo");

        javax.swing.GroupLayout tabCustomerBasicLayout = new javax.swing.GroupLayout(tabCustomerBasic);
        tabCustomerBasic.setLayout(tabCustomerBasicLayout);
        tabCustomerBasicLayout.setHorizontalGroup(
            tabCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCustomerBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomerBasic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCustomerBasicLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCustomerBasicNext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabCustomerBasicLayout.setVerticalGroup(
            tabCustomerBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCustomerBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomerBasic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomerBasicNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tabPanelCustomer.addTab("Básico", tabCustomerBasic);

        tabCustomerAddress.setBackground(new java.awt.Color(255, 255, 255));

        panelCustomerAddress.setBackground(new java.awt.Color(255, 255, 255));
        panelCustomerAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        cbCustomerAddressPublicPlaceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCustomerAddressPublicPlaceType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerAddressPublicPlaceType.setText("Tipo Logradouro:");

        lblCustomerAddressPublicPlace.setText("Logradouro:");

        lblCustomerAddressNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerAddressNumber.setText("Número:");

        lblCustomerAddressDistrict.setText("Bairro:");

        txtCustomerAddressDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerAddressDistrictActionPerformed(evt);
            }
        });

        lblCustomerAddressComplement.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerAddressComplement.setText("Complemento:");

        lblCustomerAddressState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerAddressState.setText("UF:");

        cbCustomerAddressState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCustomerAddressCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerAddressCity.setText("Cidade:");

        cbCustomerAddressCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCustomerAddressZipCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCustomerAddressZipCode.setText("CEP:");

        javax.swing.GroupLayout panelCustomerAddressLayout = new javax.swing.GroupLayout(panelCustomerAddress);
        panelCustomerAddress.setLayout(panelCustomerAddressLayout);
        panelCustomerAddressLayout.setHorizontalGroup(
            panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerAddressLayout.createSequentialGroup()
                        .addComponent(lblCustomerAddressPublicPlaceType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCustomerAddressPublicPlaceType, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustomerAddressPublicPlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerAddressPublicPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE))
                    .addGroup(panelCustomerAddressLayout.createSequentialGroup()
                        .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCustomerAddressNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustomerAddressZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustomerAddressState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustomerAddressComplement, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerAddressComplement)
                            .addGroup(panelCustomerAddressLayout.createSequentialGroup()
                                .addComponent(txtCustomerAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustomerAddressDistrict)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerAddressDistrict))
                            .addComponent(txtCustomerAddressZipCode)
                            .addGroup(panelCustomerAddressLayout.createSequentialGroup()
                                .addComponent(cbCustomerAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustomerAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCustomerAddressCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelCustomerAddressLayout.setVerticalGroup(
            panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerAddressLayout.createSequentialGroup()
                .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCustomerAddressPublicPlaceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerAddressPublicPlaceType)
                    .addComponent(lblCustomerAddressPublicPlace)
                    .addComponent(txtCustomerAddressPublicPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerAddressNumber)
                    .addComponent(txtCustomerAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerAddressDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerAddressDistrict))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerAddressComplement)
                    .addComponent(txtCustomerAddressComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCustomerAddressState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerAddressState)
                    .addComponent(lblCustomerAddressCity)
                    .addComponent(cbCustomerAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerAddressZipCode)
                    .addComponent(txtCustomerAddressZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddressNext.setText("Próximo");

        btnAddressBack.setText("Voltar");

        javax.swing.GroupLayout tabCustomerAddressLayout = new javax.swing.GroupLayout(tabCustomerAddress);
        tabCustomerAddress.setLayout(tabCustomerAddressLayout);
        tabCustomerAddressLayout.setHorizontalGroup(
            tabCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCustomerAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCustomerAddressLayout.createSequentialGroup()
                        .addComponent(btnAddressBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddressNext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabCustomerAddressLayout.setVerticalGroup(
            tabCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCustomerAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCustomerAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddressNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddressBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        tabPanelCustomer.addTab("Endereço", tabCustomerAddress);

        tabCustomerContact.setBackground(new java.awt.Color(255, 255, 255));

        paneCustomerlContact.setBackground(new java.awt.Color(255, 255, 255));
        paneCustomerlContact.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        cbCustomerContactContactType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCustomerContactContactType.setText("Tipo Contato:");

        tableCustomerContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Tipo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollCustomerContact.setViewportView(tableCustomerContact);

        btnCustomerContactNew.setText("Novo");

        btnCustomerContactDelete.setText("Del");

        btnCustomerContactSave.setText("Salvar");
        btnCustomerContactSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerContactSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCustomerlContactLayout = new javax.swing.GroupLayout(paneCustomerlContact);
        paneCustomerlContact.setLayout(paneCustomerlContactLayout);
        paneCustomerlContactLayout.setHorizontalGroup(
            paneCustomerlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCustomerlContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCustomerlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCustomerlContactLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(txtCustomerContactValue))
                    .addGroup(paneCustomerlContactLayout.createSequentialGroup()
                        .addComponent(lblCustomerContactContactType)
                        .addGap(1, 1, 1)
                        .addComponent(cbCustomerContactContactType, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollCustomerContact, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCustomerlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCustomerContactDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomerContactNew, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnCustomerContactSave, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        paneCustomerlContactLayout.setVerticalGroup(
            paneCustomerlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCustomerlContactLayout.createSequentialGroup()
                .addGroup(paneCustomerlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCustomerContactSave)
                    .addGroup(paneCustomerlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCustomerContactContactType)
                        .addComponent(cbCustomerContactContactType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustomerContactValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCustomerlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCustomerlContactLayout.createSequentialGroup()
                        .addComponent(btnCustomerContactNew, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnCustomerContactDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollCustomerContact, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        btnCustomerContactBack.setText("Voltar");
        btnCustomerContactBack.setPreferredSize(new java.awt.Dimension(71, 23));

        btnCustomerContactCustomerSave.setText("Salvar");
        btnCustomerContactCustomerSave.setPreferredSize(new java.awt.Dimension(71, 23));

        javax.swing.GroupLayout tabCustomerContactLayout = new javax.swing.GroupLayout(tabCustomerContact);
        tabCustomerContact.setLayout(tabCustomerContactLayout);
        tabCustomerContactLayout.setHorizontalGroup(
            tabCustomerContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCustomerContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCustomerContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneCustomerlContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabCustomerContactLayout.createSequentialGroup()
                        .addComponent(btnCustomerContactBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCustomerContactCustomerSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabCustomerContactLayout.setVerticalGroup(
            tabCustomerContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCustomerContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneCustomerlContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCustomerContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCustomerContactCustomerSave, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnCustomerContactBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        tabPanelCustomer.addTab("Contato", tabCustomerContact);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Cliente - Novo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelCustomer)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanelCustomer))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerAddressDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerAddressDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAddressDistrictActionPerformed

    private void btnCustomerContactSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerContactSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerContactSaveActionPerformed

    private void txtCustomerBasicNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerBasicNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerBasicNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddressBack;
    private javax.swing.JButton btnAddressNext;
    private javax.swing.JButton btnCustomerBasicNext;
    private javax.swing.JButton btnCustomerContactBack;
    private javax.swing.JButton btnCustomerContactCustomerSave;
    private javax.swing.JButton btnCustomerContactDelete;
    private javax.swing.JButton btnCustomerContactNew;
    private javax.swing.JButton btnCustomerContactSave;
    private javax.swing.JComboBox<String> cbCustomerAddressCity;
    private javax.swing.JComboBox<String> cbCustomerAddressPublicPlaceType;
    private javax.swing.JComboBox<String> cbCustomerAddressState;
    private javax.swing.JComboBox<String> cbCustomerBasicDocumentType;
    private javax.swing.JComboBox<String> cbCustomerBasicGender;
    private javax.swing.JComboBox<String> cbCustomerBasicMaritalStatus;
    private javax.swing.JComboBox<String> cbCustomerContactContactType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCustomerAddressCity;
    private javax.swing.JLabel lblCustomerAddressComplement;
    private javax.swing.JLabel lblCustomerAddressDistrict;
    private javax.swing.JLabel lblCustomerAddressNumber;
    private javax.swing.JLabel lblCustomerAddressPublicPlace;
    private javax.swing.JLabel lblCustomerAddressPublicPlaceType;
    private javax.swing.JLabel lblCustomerAddressState;
    private javax.swing.JLabel lblCustomerAddressZipCode;
    private javax.swing.JLabel lblCustomerBasicBirthDate;
    private javax.swing.JLabel lblCustomerBasicDocument;
    private javax.swing.JLabel lblCustomerBasicGender;
    private javax.swing.JLabel lblCustomerBasicMaritalSatus;
    private javax.swing.JLabel lblCustomerBasicName;
    private javax.swing.JLabel lblCustomerContactContactType;
    private javax.swing.JPanel paneCustomerlContact;
    private javax.swing.JPanel panelCustomerAddress;
    private javax.swing.JPanel panelCustomerBasic;
    private javax.swing.JScrollPane scrollCustomerContact;
    private javax.swing.JPanel tabCustomerAddress;
    private javax.swing.JPanel tabCustomerBasic;
    private javax.swing.JPanel tabCustomerContact;
    private javax.swing.JTabbedPane tabPanelCustomer;
    private javax.swing.JTable tableCustomerContact;
    private javax.swing.JTextField txtCustomerAddressComplement;
    private javax.swing.JTextField txtCustomerAddressDistrict;
    private javax.swing.JTextField txtCustomerAddressNumber;
    private javax.swing.JTextField txtCustomerAddressPublicPlace;
    private javax.swing.JFormattedTextField txtCustomerAddressZipCode;
    private javax.swing.JFormattedTextField txtCustomerBasicBirthDate;
    private javax.swing.JFormattedTextField txtCustomerBasicDocument;
    private javax.swing.JTextField txtCustomerBasicName;
    private javax.swing.JTextField txtCustomerContactValue;
    // End of variables declaration//GEN-END:variables
}
